name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - dotnet-version: '8.0.x'
          tfm: 'net8.0'

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Display dotnet version
        run: dotnet --version
      - name: Build
        run: dotnet build --configuration Release --framework ${{ matrix.tfm }} ./src/libs/FastEnum.Core/FastEnum.Core.csproj
      - name: Test
        run: dotnet test --verbosity normal --configuration Release --framework ${{ matrix.tfm }} ./src/insights/FastEnum.UnitTests/FastEnum.UnitTests.csproj